Repository wecode-bootcamp-korea/28-2nd-Barracks-frontend, pull requests merged in 2022-01, with the labels that each got.

#2 [28기 정해수] 공통으로 사용할 logo.png 추가
  public/logo/logo.png
Labels: Status: 리뷰 요청

#1 Modify: 초기셋팅 중 놓친 부분 수정
  public/data/mock.md
  public/images/mock.md
  src/components/Logo/Logo.jsx
  src/pages/Main/Main.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
  yarn.lock
Labels: Status: Accepted

#6 [28기 박윤국] Login page UI 완료
  .gitignore
  public/images/kakao_login_large_wide.png
  public/index.html
  src/Router.js
  src/index.js
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
  src/socialLogin/KakaoLogin.js
  src/styles/mixins.js
Labels: Status: 리뷰 요청

#5 [28기 정해수] 디테일페이지 컨텐츠 영역 및 버튼 컴포넌트 구현.
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/DetailArticle/DetailArticle.jsx
  src/pages/Detail/components/DetailArticle/DetailHeader.jsx
  src/pages/Detail/components/DetailArticle/DetailInformation.jsx
  src/pages/Detail/components/DetailAside/DetailAside.jsx
  src/pages/Detail/components/DetailAvatar/DetailAvatar.jsx
  src/pages/Detail/components/DetailButtons/DetailButton.jsx
  src/pages/Detail/components/DetailComments/DetailComments.jsx
  src/pages/Detail/components/DetailProfile/DetailProfile.jsx
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [28기 박윤국] Modify: 소셜 로그인 토큰 받아오기 완료
  package-lock.json
  package.json
  src/Router.js
  src/pages/Login/Login.jsx
  src/socialLogin/KakaoLogin.js
  src/socialLogin/KakaoRequest.jsx
  yarn.lock
Labels: Status: Accepted

#10 [28기 정해수] Add: 사진슬라이드 추가, 버튼 컴포넌트 분리 및 목데이터 추가
  package-lock.json
  package.json
  public/data/DetailMockData.json
  src/index.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/DetailArticle/DetailArticle.jsx
  src/pages/Detail/components/DetailArticle/DetailSlider.jsx
  src/pages/Detail/components/DetailAside/BookMarkToggleButton.jsx
  src/pages/Detail/components/DetailAside/DetailAside.jsx
  src/pages/Detail/components/DetailAside/HeartToggleButton.jsx
  src/pages/Detail/components/DetailComments/DetailComments.jsx
  src/pages/Detail/hooks/UseToggle.jsx
Labels: Status: 추가 기능 구현중

#4 [28기 한상일][Modify] 레이아웃 피드백 반영하여 수정
  package-lock.json
  package.json
  public/data/cardTempData.json
  public/data/cardTodayData.json
  public/data/mainTempData.json
  public/products/limit=8&offset=1.json
  public/products/limit=8&offset=2.json
  public/products/limit=8&offset=3.json
  public/products/limit=8&offset=4.json
  public/products/limit=8&offset=5.json
  public/products/limit=8&offset=6.json
  src/components/Card/Card.jsx
  src/components/Card/TodayStoryCard.jsx
  src/index.js
  src/pages/Main/Main.jsx
  yarn.lock
Labels: Status: 수정 요청

#8 [28기 박윤국] Implement Global Nav Bar Static UI
  package-lock.json
  package.json
  public/images/img-user-03.jpg
  public/images/img-user-default.png
  src/Router.js
  src/components/Avatar/Avatar.jsx
  src/components/Button/Button.jsx
  src/components/DropDown/SearchDropDownMenu.jsx
  src/components/DropDown/UserDropDownMenu.jsx
  src/components/GNB/ButtonGroup/GeneralUser.jsx
  src/components/GNB/ButtonGroup/UnauthorizedUser.jsx
  src/components/GNB/GNB.jsx
  src/components/GNB/NavButtonGroup.jsx
  src/components/GNB/SearchInput.jsx
  src/components/Layout/Layout.jsx
  src/components/Logo/Logo.jsx
  src/hooks/useOutsideClick.js
  src/index.js
  src/pages/Detail/components/DetailButtons/DetailButton.jsx
  src/pages/Login/Login.jsx
  src/styles/theme.js
  yarn.lock
Labels: Status: 리뷰 요청

#12 [28기 정해수] Add: 클립보드 복사기능 추가 및 댓글 페이지네이션 구현, useFetch 커스텀 훅 사용
  package-lock.json
  public/data/DetailMockData.json
  public/data/comment/offset=0&limit=5.json
  public/data/comment/offset=5&limit=5.json
  public/index.html
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/DetailArticle/DetailArticle.jsx
  src/pages/Detail/components/DetailArticle/DetailInformation.jsx
  src/pages/Detail/components/DetailArticle/DetailSlider.jsx
  src/pages/Detail/components/DetailAside/BookMarkToggleButton.jsx
  src/pages/Detail/components/DetailAside/ClipboardButton.jsx
  src/pages/Detail/components/DetailAside/DetailAside.jsx
  src/pages/Detail/components/DetailAside/HeartToggleButton.jsx
  src/pages/Detail/components/DetailAvatar/DetailAvatar.jsx
  src/pages/Detail/components/DetailComments/CommentWrapper.jsx
  src/pages/Detail/components/DetailComments/Comments.jsx
  src/pages/Detail/components/DetailComments/DetailComments.jsx
  src/pages/Detail/components/DetailComments/Pagination.jsx
  src/pages/Detail/hooks/useFetch.jsx
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#13 [28기 한상일] [Modify] 무한스크롤 기능 추가 + 필터 기능 구현중
  package-lock.json
  public/data/Mains/ImageSlideData.json
  public/data/Mains/Mains.json
  public/data/cardTempData.json
  public/data/cardTodayData.json
  public/products/limit=8&offset=1.json
  public/products/limit=8&offset=2.json
  public/products/limit=8&offset=3.json
  public/products/limit=8&offset=4.json
  public/products/limit=8&offset=5.json
  public/products/limit=8&offset=6.json
  src/components/Card/Card.jsx
  src/pages/Main/Filter/Filter.jsx
  src/pages/Main/Filter/FilterBar.jsx
  src/pages/Main/Filter/FilterList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainPagination/PhotoCard.jsx
  src/pages/Main/topCarousel/topCarousel.jsx
  yarn.lock
Labels: Status: 리뷰 요청

#16 [28기 정해수] Modify: 디테일 페이지 및 댓글 기능 백엔드 통신완료 후 수정사항 진행중.
  public/data/comment/offset=5&limit=5.json
  src/Router.js
  src/components/Avatar/Avatar.jsx
  src/pages/Detail/components/DetailArticle/DetailArticle.jsx
  src/pages/Detail/components/DetailAside/ClipboardButton.jsx
  src/pages/Detail/components/DetailComments/CommentInputWrapper.jsx
  src/pages/Detail/components/DetailComments/CommentWrapper.jsx
  src/pages/Detail/components/DetailComments/Comments.jsx
  src/pages/Detail/components/DetailComments/DetailComments.jsx
  src/pages/Detail/components/DetailProfile/DetailProfile.jsx
  src/pages/Detail/hooks/useFetch.jsx
Labels: Status: 리뷰 요청, Status: 도움 요청

#14 [28기 박윤국] Add: NewPost 전송폼 페이지 제작
  package-lock.json
  package.json
  src/Router.js
  src/components/Avatar/Avatar.jsx
  src/components/Button/Button.jsx
  src/components/DropDown/UserDropDownMenu.jsx
  src/components/GNB/ButtonGroup/GeneralUser.jsx
  src/components/GNB/ButtonGroup/UnauthorizedUser.jsx
  src/components/GNB/NavButtonGroup.jsx
  src/components/Logo/Logo.jsx
  src/components/Select/Select.jsx
  src/config.js
  src/pages/NewPost/CardItemDescriptionKeywordInput.jsx
  src/pages/NewPost/CardListItem.jsx
  src/pages/NewPost/ContainerCardList.jsx
  src/pages/NewPost/MetadataForm.jsx
  src/pages/NewPost/NewPost.jsx
  src/pages/NewPost/PostDataForm.jsx
  src/socialLogin/KakaoRequest.jsx
  yarn.lock
Labels: Status: 리뷰 요청

#19 es-lint 수정
  package-lock.json
  src/config.js
  src/pages/Detail/components/DetailComments/DetailComments.jsx
  src/pages/Detail/hooks/useDetail.jsx
  src/pages/Main/Filter/FilterBar.jsx
  src/pages/Main/MainPagination/PhotoCard.jsx
  yarn.lock
Labels: Status: 리뷰 요청
